name: Tag
on:
  push:
    branches: [ master ]

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Dhall
      uses: dhall-lang/setup-dhall@v4
    - env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        LAST_RELEASE=$(hub release -L 1)
        LOCAL_VERSION=$(dhall text <<< 'let a = ./app.dhall in "v${a.version}"')
        echo "main version is $LAST_RELEASE and current version is $LOCAL_VERSION"
        if [ $LAST_RELEASE != $LOCAL_VERSION ];then
          git tag ${LOCAL_VERSION}
          git push origin ${LOCAL_VERSION}
          hub release create -m "${LOCAL_VERSION}" "${LOCAL_VERSION}"
        fi
