name: Release
on:
  push:
    branches: [ master ]

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Dhall
      uses: dhall-lang/setup-dhall@v4
    - name: Setup Hub
      uses: Geertvdc/setup-hub@v1.0.0
    - run: |
        LAST_RELEASE=$(hub release -L 1)
        LOCAL_VERSION=$(dhall text <<< 'let a = ./app.dhall in "v${a.version}"')
        echo "main version is $LAST_RELEASE and current version is $LOCAL_VERSION"
        if [ $LAST_RELEASE != $LOCAL_VERSION ];then
          hub release create -m "${LOCAL_VERSION}" -m "$(git log "${LAST_RELEASE}"..HEAD --pretty="format:- %b %s")" "${LOCAL_VERSION}"
        fi
